#! /bin/sh

bspc config window_gap 120;

feh --bg-fill ~/images/nookac.png

$HOME/.config/polybar/launch.sh

sxhkd &

picom --config ~/.config/compton/picom.conf &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width	10
bspc config window_gap          35
bspc config border_radius	12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#night light
killall redshift ; redshift &

#spotify daemon and launch
killall spotifyd ; spotifyd &
bspc rule -a termite -e spt desktop=^1

termite -e spt &

bspc rule firefox desktop=^2
#firefox &
